# Navigation Links

main:
  - name: 'About'
    url: about
    weight: 10

  - name: 'Declaration'
    url: declaration
    weight: 20

  - name: 'Signatories'
    url: signatories
    weight: 30

  - name: 'Toolkit'
    url: toolkit
    weight: 40

  - name: 'News'
    url: news
    weight: 50

  - name: 'Contact'
    url: contact
    weight: 60

main_right:
  - name: 'Get Involved'
    url: get-involved
    weight: 10
