# Navigation Links

main:
  - name: 'About'
    identifier: 'about'
    url: about
    weight: 10

  - name: 'About ADORE.software'
    parent: 'about'
    url: about/about-adore
    weight: 11

  - name: 'Governance'
    parent: 'about'
    url: about/governance
    weight: 12

  - name: 'Process'
    parent: 'about'
    url: about/process
    weight: 13

  - name: 'FAQ'
    parent: 'about'
    url: faq
    weight: 14

  - name: 'Declaration'
    url: declaration
    weight: 20

  - name: 'Signatories'
    url: signatories
    weight: 30

  - name: 'Toolkit'
    url: toolkit
    weight: 40

  - name: 'News'
    url: news
    weight: 50

  - name: 'Contact'
    url: contact
    weight: 60

main_right:
  - name: 'Get Involved'
    url: get-involved
    weight: 10
